# Generated by Django 3.2.1 on 2021-05-05 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ('question', 'choice_text')},
        ),
    ]
