# Generated by Django 3.2.1 on 2021-06-07 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnary', '0003_alter_answer_answer_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Translations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=64)),
                ('translation', models.CharField(max_length=500)),
                ('key_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnary.keywords')),
            ],
        ),
    ]
