BBBBBBB BBBBBBBBBBB

BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXX
                BBBBBBBBBB
                XXXX XXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX
        XXXXXX
        XXX XXXXXXXXXXXXX
        XXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXX
                XXXX XX XXXXXXX X XX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBXXXXXX XX XXXXXXX
            XXXXXXXX
        XXXXXX
    XXXXXX
BBBBBBBB