BBBBBBB BBBBBBBBBBB

BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
                
            XXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXX
        XXXXXXX
        XXX XXXXXXXXXXXXX
        XXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXX XX XXXXXXX X XX XXXXXXXXXXXX XXXXXXBBB BBBBBBBXXXXXX XXXXXX
            XXXXXXXX
        XXXXXX
    XXXXXX
BBBBBBBB